name: PR upstreams → Upstream-Acer

on:
  schedule:
    - cron: "30 */12 * * *"
  workflow_dispatch:

jobs:
  torvalds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PR torvalds → Upstream-Acer
        uses: peter-evans/create-pull-request@v6
        with:
          base: Upstream-Acer
          branch: torvalds-base
          title: "sync: torvalds → Upstream-Acer"
          body: |
            Sync automático desde torvalds/linux.
          labels: torvalds, upstream
          signoff: true
          auto-merge: true
          merge-method: merge

  sunxi:
    runs-on: ubuntu-latest
    needs: torvalds
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PR sunxi → Upstream-Acer
        uses: peter-evans/create-pull-request@v6
        with:
          base: Upstream-Acer
          branch: sunxi-base
          title: "sync: sunxi → Upstream-Acer"
          body: |
            Sync automático desde jwrdegoede/linux-sunxi.
          labels: sunxi, upstream
          signoff: true
          auto-merge: true
          merge-method: merge
